---
# Export tasks

- name: Check exported certificates
  stat:
    path: "{{ java_keystore_item.path }}"
  when: >-
    java_keystore_item.state | default("present")
    in ["self-signed", "exported"]
  register: java_keystore_check_exported_result
  loop: "{{ java_keystore_keys }}"
  loop_control:
    loop_var: java_keystore_item
    index_var: java_keystore_index
    label: "{{ java_keystore_item.alias }}"

- name: Export certificates
  command: >-
    keytool
    -noprompt
    -export
    -alias {{ java_keystore_item.alias }}
    -keystore {{ java_keystore_path }}
    -storepass {{ java_keystore_password }}
    -rfc
    -file {{ java_keystore_item.path }}
  when:
    - >-
      java_keystore_item.state | default("present")
      in ["self-signed", "exported"]
    - >-
      java_keystore_item.path | default("") | length > 0
    - >-
      not java_keystore_check_exported_result.results[java_keystore_index]
          .stat.exists
      or java_keystore_setup_certs_result.results[java_keystore_index]
         is changed
  loop: "{{ java_keystore_keys }}"
  loop_control:
    loop_var: java_keystore_item
    index_var: java_keystore_index
    label: "{{ java_keystore_item.alias }}"
  no_log: "{{ java_keystore_no_log | bool }}"
