---
# Gather fingerprints tasks

- name: Gather fingerprints certificates files
  openssl_certificate_info:
    path: "{{ java_keystore_item.path }}"
  when:
    - not java_keystore_no_certs_fingerprints | default(false) | bool
    - not java_keystore_item.state | default("present") == "self-signed"
    - java_keystore_item.path | default("") | length > 0
  register: java_keystore_certs_fingerprints_result
  loop: "{{ java_keystore_keys }}"
  loop_control:
    loop_var: java_keystore_item
    index_var: java_keystore_index
    label: "{{ java_keystore_item.path }}"

- name: Gather fingerprints from keystore
  shell: >-
    keytool
    -noprompt
    -list
    -alias {{ keystore_item.alias }}
    -keystore {{ java_keystore_path }}
    -storepass {{java_keystore_password }}
    -keypass {{ keystore_item.password }}
    -v
    | grep "SHA256:"
    | sed -r "s#.*SHA256: *(.*)#\1#g"
  changed_when: no
  args:
    warn: no
  register: java_keystore_fingerprints_result
  loop: "{{ java_keystore_keys }}"
  loop_control:
    loop_var: keystore_item
    label: "{{ keystore_item.alias }}"
  no_log: "{{ java_keystore_no_log | bool }}"
