---
# Gather fingerprints tasks

- name: Gather fingerprints from certificates files
  shell: >-
    set -o pipefail ;
    {{ java_keystore_item_cmd_map
       [(java_keystore_item.path | splitext).1] }}
  args:
    warn: no
  when:
    - >-
      not java_keystore_no_certs_fingerprints | default(false) | bool
    - >-
      not java_keystore_item.state | default("present")
      in ["self-signed", "exported"]
    - java_keystore_item.path | default("") | length > 0
  register: java_keystore_certs_fingerprints_result
  changed_when: no
  loop: "{{ java_keystore_keys }}"
  loop_control:
    loop_var: java_keystore_item
    index_var: java_keystore_index
    label: "{{ java_keystore_item.path }}"
  vars:
    java_keystore_item_cmd_crt: >-
      openssl x509
      -in {{ java_keystore_item.path }}
      -noout
      -fingerprint
      -sha256
      | sed -r "s#.*=(.*)#\1#" | tr "[:upper:]" "[:lower:]"

    java_keystore_item_cmd_p12: >-
      openssl pkcs12
      -in {{ java_keystore_item.path }}
      -nodes
      -nokeys
      -passin pass:{{ java_keystore_item.password | default("") }}
      | openssl x509 -noout -fingerprint -sha256
      | sed -r "s#.*=(.*)#\1#"
      | tr "[:upper:]" "[:lower:]"

    java_keystore_item_cmd_map:
      .crt: "{{ java_keystore_item_cmd_crt }}"
      .p12: "{{ java_keystore_item_cmd_p12 }}"
      .pem: "{{ java_keystore_item_cmd_crt }}"

- name: Gather fingerprints from keystore
  shell: >-
    set -o pipefail ;
    keytool
    -noprompt
    -list
    -alias {{ keystore_item.alias }}
    -keystore {{ java_keystore_path }}
    -storepass {{ java_keystore_password }}
    {{ java_keystore_keypass_arg }}
    -v
    | grep "SHA256:"
    | sed -r "s#.*SHA256: *(.*)#\1#g"
  changed_when: no
  args:
    warn: no
  register: java_keystore_fingerprints_result
  loop: "{{ java_keystore_keys }}"
  loop_control:
    loop_var: keystore_item
    label: "{{ keystore_item.alias }}"
  failed_when: no
  no_log: "{{ java_keystore_no_log | bool }}"
  vars:
    java_keystore_keypass_arg: >-
      {{ (java_keystore_item.password | default("") | length > 0)
         | ternary("-keypass " + java_keystore_item.password | default(""),
                   "") }}
