---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check certificate files
      stat:
        path: "{{ item }}"
      loop: "{{ crt_files }}"
      register: check_certs_results

    - name: Check PKCS12 files
      stat:
        path: "{{ item }}"
      loop: "{{ p12_files }}"
      register: check_pkeys_results

    - name: Assert certificate files exist
      assert:
        quiet: yes
        that: check_certs_results.results[index].stat.exists
      loop: "{{ crt_files }}"
      loop_control:
        index_var: index

    - name: Assert PKCS12 files exist
      assert:
        quiet: yes
        that: check_pkeys_results.results[index].stat.exists
      loop: "{{ p12_files }}"
      loop_control:
        index_var: index
  vars:
    crt_files: "{{ java_keystore_keys | map(attribute='path') | list }}"
    p12_files: >-
      {{ java_keystore_keys
         | map(attribute='path')
         | list
         | map("regex_replace", "\.crt", ".p12") }}
