---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check certificate files
      stat:
        path: "{{ item }}"
      loop: "{{ certificate_files }}"
      register: check_certs_results

    - name: Assert certificate files exist
      assert:
        that: check_certs_results.results[index].stat.exists
      loop: "{{ certificate_files }}"
      loop_control:
        index_var: index
  vars:
    certificate_files: "{{ java_keystore_keys | map(attribute='path') | list }}"
